# [host] 服务域名
host:

# [port] 服务端口
port:

# [application.yaml] 配置文件重读跟新频率
profile_refresh_rate:

# [postgres] 数据库配置
postgres:
  host:
  username:
  password:
  port:
  db_name:
  pool_size:

#[redis] 数据库配置
redis:
  scheme:
  host:
  username:
  password:
  port:
  db:
  pool_size:

#[rabbit-mq] 队列配置
rabbit:
  scheme:
  host:
  port:
  username:
  password:
  vhost: %2f
#分期分率: {"分期":"费率"}
installment_fee_rate:
  3: 1.5
  6: 2
  12: 2.5
#最低分期金额
min_installment_amount: 300
#预期日息
installment_fine_rate: 0.05
#[alipay] 支付配置
alipay:
  app_id:
  private_key:
  return_url:
  notify_url:
#[elasticsearch] 配置, host配置后可不用配置其他三项
elasticsearch:
  host:
  cloud_id:
  username:
  password: