# [host] 服务域名
host:

# [port] 服务端口
port:

# [application.yaml] 配置文件重读跟新频率
profile_refresh_rate:

# [postgres] 数据库配置
postgres:
  host:
  username:
  password:
  port:
  db_name:
  pool_size:

#[redis] 数据库配置
redis:
  host:
  username:
  password:
  port:
  db:
  pool_size: